# Generated by Django 4.0 on 2022-01-02 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.ForeignKey(db_column='document_type', on_delete=django.db.models.deletion.CASCADE, to='category.document'),
        ),
    ]
