# Generated by Django 4.0 on 2022-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
