# Generated by Django 4.0 on 2022-02-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_email_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
