# Generated by Django 4.0 on 2022-03-04 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_email_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, default=0)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=20)),
                ('employee_first_name', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_department', models.CharField(max_length=100)),
                ('employee_position', models.CharField(max_length=100)),
                ('employee_is_management', models.CharField(max_length=20)),
                ('employee_access_to_request', models.CharField(max_length=20)),
                ('employee_is_admin', models.CharField(max_length=20)),
                ('employee_admin_descr', models.TextField(blank=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
