# Generated by Django 4.0 on 2022-02-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_document_documentvariation'),
        ('accounts', '0007_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='department',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='department',
            field=models.ManyToManyField(to='category.Department'),
        ),
    ]
