# Generated by Django 4.0 on 2022-02-21 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_document_documentvariation'),
        ('accounts', '0008_remove_userpermission_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='documents',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.documentvariation'),
        ),
    ]
