# Generated by Django 4.0 on 2022-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_document_documentvariation'),
        ('accounts', '0009_remove_userpermission_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpermission',
            name='documents',
        ),
        migrations.AddField(
            model_name='userpermission',
            name='documents',
            field=models.ManyToManyField(to='category.DocumentVariation'),
        ),
    ]
