# Generated by Django 4.0 on 2022-02-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_userpermission_documents_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
