# Generated by Django 4.0 on 2022-02-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_document_documentvariation'),
        ('accounts', '0011_delete_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='category.department'),
        ),
    ]
