# Generated by Django 4.0 on 2022-03-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='request_access',
            field=models.BooleanField(default=False),
        ),
    ]
