# Generated by Django 4.0 on 2022-02-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_file'),
        ('category', '0003_documentsection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentVariation',
        ),
    ]
