# Generated by Django 4.0 on 2022-03-10 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_document_documentvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentvariation',
            name='document_section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.documentsection'),
        ),
    ]
