# Generated by Django 4.0 on 2022-01-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KISDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kis_document_id', models.CharField(max_length=20, unique=True)),
                ('kis_document_name', models.CharField(max_length=200)),
                ('kis_document_file', models.FileField(upload_to='kis_documents/%Y/%m/%d/')),
                ('kis_document_date', models.CharField(max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.department')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Procedure',
        ),
    ]
