# Generated by Django 4.0 on 2022-01-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_kisdocument_delete_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kisdocument',
            name='kis_document_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
