# Generated by Django 4.0 on 2022-02-18 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_documentsection'),
        ('documents', '0003_alter_kisdocument_kis_document_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=100, unique=True)),
                ('document_name', models.CharField(max_length=200)),
                ('document_file', models.FileField(upload_to='kis_documents/%Y/%m/%d/')),
                ('document_date', models.CharField(max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.department')),
                ('document_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.documentsection')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.document')),
            ],
        ),
        migrations.DeleteModel(
            name='KISDocument',
        ),
    ]
