# Generated by Django 4.0 on 2021-12-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_procedure_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_file',
            field=models.FileField(upload_to='procedures/%Y/%m/%d/'),
        ),
    ]
