# Generated by Django 4.0 on 2022-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_delete_kisdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
