# Generated by Django 4.0 on 2022-02-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
