# Generated by Django 4.0 on 2022-02-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_access_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='access_for_all',
        ),
    ]
