# Generated by Django 4.0 on 2022-02-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_document_access_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_for_all',
            field=models.BooleanField(default=False),
        ),
    ]
